# Imported Container Apps Resources
# Generated by Cloudgeni Agent

# Import Resource Group
import {
  id = "/subscriptions/d647bcfd-4832-43d4-b02c-a82aeb620c2a/resourceGroups/rg-aca0410f516-northeurope"
  to = azurerm_resource_group.imported_rg_aca
}

resource "azurerm_resource_group" "imported_rg_aca" {
  name     = "rg-aca0410f516-northeurope"
  location = "northeurope"

  tags = {
    demo    = "cloud-import"
    agent   = "codex"
    created = "2026-04-10"
    purpose = "aca-import"
  }
}

# Import Virtual Network
import {
  id = "/subscriptions/d647bcfd-4832-43d4-b02c-a82aeb620c2a/resourceGroups/rg-aca0410f516-northeurope/providers/Microsoft.Network/virtualNetworks/vnet-aca0410f516"
  to = azurerm_virtual_network.imported_vnet_aca
}

resource "azurerm_virtual_network" "imported_vnet_aca" {
  name                = "vnet-aca0410f516"
  resource_group_name = azurerm_resource_group.imported_rg_aca.name
  location            = azurerm_resource_group.imported_rg_aca.location
  address_space       = ["10.42.0.0/16"]

  tags = {
    demo    = "cloud-import"
    agent   = "codex"
    created = "2026-04-10"
    purpose = "aca-import"
  }
}

# Import Subnet
import {
  id = "/subscriptions/d647bcfd-4832-43d4-b02c-a82aeb620c2a/resourceGroups/rg-aca0410f516-northeurope/providers/Microsoft.Network/virtualNetworks/vnet-aca0410f516/subnets/snet-aca-infra"
  to = azurerm_subnet.imported_subnet_aca_infra
}

resource "azurerm_subnet" "imported_subnet_aca_infra" {
  name                 = "snet-aca-infra"
  resource_group_name  = azurerm_resource_group.imported_rg_aca.name
  virtual_network_name = azurerm_virtual_network.imported_vnet_aca.name
  address_prefixes     = ["10.42.0.0/23"]

  # Delegation required for Container Apps but not supported in azurerm 3.50.0
  # Managed manually or through Azure CLI
}

# Import Storage Account
import {
  id = "/subscriptions/d647bcfd-4832-43d4-b02c-a82aeb620c2a/resourceGroups/rg-aca0410f516-northeurope/providers/Microsoft.Storage/storageAccounts/saaca0410f516nort"
  to = azurerm_storage_account.imported_sa_aca
}

resource "azurerm_storage_account" "imported_sa_aca" {
  name                     = "saaca0410f516nort"
  resource_group_name      = azurerm_resource_group.imported_rg_aca.name
  location                 = azurerm_resource_group.imported_rg_aca.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  account_kind             = "StorageV2"
  access_tier              = "Hot"
  min_tls_version          = "TLS1_2"

  allow_nested_items_to_be_public = false
  enable_https_traffic_only       = true

  tags = {
    demo    = "cloud-import"
    agent   = "codex"
    created = "2026-04-10"
    purpose = "aca-import"
  }
}

# Import Container Apps Managed Environment
# NOTE: azurerm_container_app_environment has limited support in 3.50.0
# - Requires log_analytics_workspace_id but actual resource doesn't have one
# - Missing zone_redundant_enabled and workload_profile support
# Uncomment after updating provider version to >= 3.70.0

# import {
#   id = "/subscriptions/d647bcfd-4832-43d4-b02c-a82aeb620c2a/resourceGroups/rg-aca0410f516-northeurope/providers/Microsoft.App/managedEnvironments/cae-aca0410f516"
#   to = azurerm_container_app_environment.imported_cae_aca
# }

# resource "azurerm_container_app_environment" "imported_cae_aca" {
#   name                           = "cae-aca0410f516"
#   location                       = "northeurope"
#   resource_group_name            = azurerm_resource_group.imported_rg_aca.name
#   infrastructure_subnet_id       = azurerm_subnet.imported_subnet_aca_infra.id
#   internal_load_balancer_enabled = false
#
#   tags = {
#     demo    = "cloud-import"
#     agent   = "codex"
#     created = "2026-04-10"
#     purpose = "aca-import"
#   }
# }

# Import Container App
# NOTE: Depends on azurerm_container_app_environment which is commented out
# Uncomment after Container App Environment is successfully imported

# import {
#   id = "/subscriptions/d647bcfd-4832-43d4-b02c-a82aeb620c2a/resourceGroups/rg-aca0410f516-northeurope/providers/Microsoft.App/containerApps/app-aca0410f516"
#   to = azurerm_container_app.imported_app_aca
# }

# resource "azurerm_container_app" "imported_app_aca" {
#   name                         = "app-aca0410f516"
#   container_app_environment_id = azurerm_container_app_environment.imported_cae_aca.id
#   resource_group_name          = azurerm_resource_group.imported_rg_aca.name
#   revision_mode                = "Single"
#   workload_profile_name        = "Consumption"
#
#   template {
#     min_replicas = 0
#     max_replicas = 1
#
#     container {
#       name   = "app-aca0410f516"
#       image  = "mcr.microsoft.com/azuredocs/containerapps-helloworld:latest"
#       cpu    = 0.25
#       memory = "0.5Gi"
#     }
#   }
#
#   ingress {
#     external_enabled = true
#     target_port      = 80
#     transport        = "auto"
#
#     traffic_weight {
#       latest_revision = true
#       percentage      = 100
#     }
#   }
#
#   tags = {
#     demo    = "cloud-import"
#     agent   = "codex"
#     created = "2026-04-10"
#     purpose = "aca-import"
#   }
# }

# Import Container App Job
# NOTE: azurerm_container_app_job requires provider version >= 3.51.0
# Current version is ~> 3.50.0, so this resource is commented out
# Uncomment after updating provider version in backend.tf

# import {
#   id = "/subscriptions/d647bcfd-4832-43d4-b02c-a82aeb620c2a/resourceGroups/rg-aca0410f516-northeurope/providers/Microsoft.App/jobs/job-aca0410f516"
#   to = azurerm_container_app_job.imported_job_aca
# }

# resource "azurerm_container_app_job" "imported_job_aca" {
#   name                         = "job-aca0410f516"
#   location                     = "northeurope"
#   resource_group_name          = azurerm_resource_group.imported_rg_aca.name
#   container_app_environment_id = azurerm_container_app_environment.imported_cae_aca.id
#   workload_profile_name        = "Consumption"
#
#   replica_timeout_in_seconds = 300
#   replica_retry_limit        = 0
#
#   manual_trigger_config {
#     parallelism              = 1
#     replica_completion_count = 1
#   }
#
#   template {
#     container {
#       name   = "job-aca0410f516"
#       image  = "mcr.microsoft.com/k8se/quickstart-jobs:latest"
#       cpu    = 0.25
#       memory = "0.5Gi"
#     }
#   }
#
#   tags = {
#     demo    = "cloud-import"
#     agent   = "codex"
#     created = "2026-04-10"
#     purpose = "aca-import"
#   }
# }
